---
language: python
python: "2.7"
sudo: required
dist: trusty

before_install:
  # Add required repos
  - sudo apt-add-repository 'deb http://archive.ubuntu.com/ubuntu trusty main universe multiverse restricted'
  # Make sure everything's up to date.
  - sudo apt-get update -qq
  - sudo apt-get install -y software-properties-common
  - sudo apt-get install -y ubuntu-cloud-keyring
  - sudo add-apt-repository -y cloud-archive:mitaka
  - sudo apt-get update -qq


install:
  # Install Ansible.
  - pip install ansible
  - sudo apt-get install -y python-openstackclient

  # Add ansible.cfg to pick up roles path.
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"


script:
  # Check the role/playbook's syntax.
  - ansible-playbook -i tests/inventory_local tests/test.yml --syntax-check

  # Run the role/playbook with ansible-playbook.
  - >
    ansible-playbook -i tests/inventory_local tests/test.yml --connection=local
    --sudo

  # Test role idempotency
  - >
    ansible-playbook -i tests/inventory_local tests/test.yml --connection=local
    --sudo | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  # Test Keystone setup
  - >
    openstack --os-password 'admin password' --os-auth-url http://localhost:35357/v2.0
    --os-username admin --os-tenant-name admin
    service list | grep keystone

  - >
    openstack --os-password 'admin password' --os-auth-url http://localhost:35357/v2.0
    --os-username admin --os-tenant-name admin
    endpoint list

  # Cat logs
  - cat /var/log/apache2/keystone* 
