---

#
# Copyright (c) 2014 Davide Guerri <davide.guerri@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

- name: Create keystone admin user in admin tenant
  keystone_user: user=admin
                 tenant=admin
                 password="{{ admin_pass }}"
                 email=admin@localhost
                 endpoint="http://{{ keystone_hostname }}:{{ keystone_admin_port }}/v2.0"
                 token="{{ admin_token }}"

- name: Create keystone demo user in demo tenant
  keystone_user: user=demo
                 tenant=demo
                 password="{{ demo_pass }}"
                 email=demo@localhost
                 endpoint="http://{{ keystone_hostname }}:{{ keystone_admin_port }}/v2.0"
                 token="{{ admin_token }}"
