---

- meta: flush_handlers

- name: WSGI Tell apache to use the hostname as the servername
  lineinfile:
    dest: "{{ webserver_conf_path }}"
    line: "ServerName {{ keystone_hostname }}"

- name: WSGI Create the WSGI Keystone configuration file
  template:
    src: wsgi-keystone.conf
    dest: "{{ webserver_new_conf_dir_path }}/wsgi-keystone.conf"

- name: WSGI Enable the identity service virtual hosts
  when: ansible_os_family == "Debian"
  file:
    src: /etc/apache2/sites-available/{{ item.name }}
    dest: /etc/apache2/sites-enabled/{{ item.name }}
    state: link
  with_items:
    - name: wsgi-keystone.conf
  notify:
    - Use WSGI

- name: WSGI Setup directory structure
  file:
    path: "{{ keystone_cgibin_dir }}"
    state: directory

- name: WSGI copy the components from the upstream repository
  get_url:
    url: "{{ keystone_upstream_wsgi_components }}"
    dest: "{{ keystone_cgibin_dir }}/{{ item }}"
  with_items:
    - "{{ keystone_wsgi_main_name }}"
    - "{{ keystone_wsgi_admin_name }}"

- name: WSGI Fix ownership and permissions
  file:
    path: "{{ keystone_cgibin_dir }}"
    owner: keystone
    group: keystone
    mode: 0755
    recurse: yes

- name: WSGI Ensure webserver is running
  service:
    name: "{{ webserver_service }}"
    state: started
